import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import Menu from "@/components/client/menu";

import CartsProvider from "@/providers/cartsProvider";
import AuthProvider from "@/providers/authProvider";
import Footer from "@/components/client/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartsProvider>
        <AuthProvider>
          <Menu />
          {children}
          </AuthProvider>
        </CartsProvider>
        <Footer />
      </body>
    </html>
  );
}
